[project]
name = "ideon-lunch"
version = "0.1.0"
description = "Create weekly lunch menu .ics file for Ideon restaurants"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "icalendar>=6.1.2",
    "python-dateutil>=2.9.0.post0",
    "scrapy>=2.12.0",
]
